spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:        # Vault가 주입
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: snuclear-valkey
      port: 6379
      password:

jwt:
  secret:       # Vault가 주입
  expiration-in-ms: 86400000

server:
  port: 8080

management:
  metrics:
    tags:
      env: dev   # Grafana에서 dev/prod 구분

oci:
  vault:
    secret-ids: "ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqano5ocm3fee2ktmqz6wfyp45qegophj2gzmmwlpesejua"

course-sync:
  auto:
    fixedDelayMillis: 10800000
  sugang:
    excelUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceExcel.action"
    refererUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceSrch.action"
    pageSize: 9999
    language: "ko"
    connectTimeoutMillis: 5000
    readTimeoutMillis: 30000
  defaultTarget:
    year: 2026
    semester: SUMMER
